In [2]:
import numpy as np
import pandas as pd

In [38]:
DrugData = pd.read_csv('DtcDrugTargetInteractions Jan 2019.csv')
pd.isnull(DrugData);

C:\Users\willi\Anaconda3\envs\data-x\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,1,2,3,8,14,21,22,23,24,25,26,27,30,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [39]:
#print(DrugData['substrate_value'].isnull().sum())
DrugDatana = DrugData.dropna(subset = ['standard_type'])
DrugDatakd = DrugDatana[DrugDatana.standard_type.str.contains('Kd' or 'KD')]

In [40]:
DrugDatakd.to_csv(r'C:\Users\willi\wx_data_x_s19\KinaseDataKdonly.csv')

In [42]:
print(len(DrugDatakd['standard_units']))

3138

In [43]:
for columns in DrugDatakd:
    if DrugDatakd[columns].isna().sum() == 3138:
        DrugDatakd = DrugDatakd.drop([columns], axis = 1)

In [44]:
DrugDatakd.to_csv(r'C:\Users\willi\wx_data_x_s19\KinaseData_Kd_noemptycolumns_2.csv')

**START USING FROM HERE**

In [1]:
#New Dataset 
import numpy as np
import pandas as pd
DrugDatakd = pd.read_csv('KinaseData_Kd_noemptycolumns.csv')

In [2]:
for columns in DrugDatakd:
    print('The number of empty values in column',columns,'is',DrugDatakd[columns].isna().sum())
print(DrugDatakd['standard_units'].unique())

The number of empty values in column Unnamed: 0 is 0
The number of empty values in column compound_id is 1025
The number of empty values in column standard_inchi_key is 958
The number of empty values in column compound_name is 2848
The number of empty values in column target_id is 0
The number of empty values in column target_pref_name is 0
The number of empty values in column gene_names is 915
The number of empty values in column pubmed_id is 782
The number of empty values in column standard_type is 0
The number of empty values in column standard_relation is 0
The number of empty values in column standard_value is 0
The number of empty values in column standard_units is 0
The number of empty values in column activity_comment is 2565
The number of empty values in column ep_action_mode is 3093
The number of empty values in column assay_format is 2996
The number of empty values in column assaytype is 1988
The number of empty values in column assay_subtype is 3092
The number of empty values in column inhibitor_type is 3078
The number of empty values in column detection_tech is 3101
The number of empty values in column assay_description is 1152
The number of empty values in column title is 1151
The number of empty values in column journal is 1795
The number of empty values in column doc_type is 1152
['NM' "10'-3/S" "10'-2/S" "10'-1/S" '/S' '1/S' "10'-4/S" "10'3/S" "10'1/S"]

In [3]:
#Replicating the Stanford Project Dataset
DrugDatakd = DrugDatakd.drop(['Unnamed: 0'], axis=1)
DrugDatakd = DrugDatakd.drop(['compound_name'], axis=1)
DrugDatakd = DrugDatakd.drop(['target_pref_name'], axis=1)
DrugDatakd = DrugDatakd.drop(['gene_names'], axis=1)
DrugDatakd = DrugDatakd.drop(['pubmed_id'], axis=1)
DrugDatakd = DrugDatakd.drop(['activity_comment'], axis=1)
DrugDatakd = DrugDatakd.drop(['ep_action_mode'], axis=1)
DrugDatakd = DrugDatakd.drop(['assay_subtype'], axis=1)
DrugDatakd = DrugDatakd.drop(['inhibitor_type'], axis=1)
DrugDatakd = DrugDatakd.drop(['detection_tech'], axis=1)
DrugDatakd = DrugDatakd.drop(['assay_description'], axis=1)
DrugDatakd = DrugDatakd.drop(['title'], axis=1)
DrugDatakd = DrugDatakd.drop(['journal'], axis=1)
DrugDatakd = DrugDatakd.drop(['doc_type'], axis=1)

In [4]:
print(list(DrugDatakd))

['compound_id', 'standard_inchi_key', 'target_id', 'standard_type', 'standard_relation', 'standard_value', 'standard_units', 'assay_format', 'assaytype']

In [5]:
#Droppung Units I dont understand (1/s) and drop standard_units column
DrugDatakd=DrugDatakd[DrugDatakd['standard_units'].str.contains('NM')]
DrugDatakd=DrugDatakd.drop(['standard_units'], axis=1)

In [6]:
DrugDatakd.shape

(3017, 8)

In [7]:
DrugDatakd_strings = DrugDatakd.select_dtypes(include=[object])

In [8]:
DrugDatakd_strings.shape

(3017, 7)

In [9]:
DrugDatakd_strings.columns

Index(['compound_id', 'standard_inchi_key', 'target_id', 'standard_type',
       'standard_relation', 'assay_format', 'assaytype'],
      dtype='object')

In [11]:
for columns in DrugDatakd_strings:
    print('The number of empty values in column',columns,'is',DrugDatakd_strings[columns].isna().sum())
DrugDatakd.to_csv(r'C:\Users\willi\wx_data_x_s19\Stanford_Dataset_Replication.csv')

The number of empty values in column compound_id is 1025
The number of empty values in column standard_inchi_key is 899
The number of empty values in column target_id is 0
The number of empty values in column standard_type is 0
The number of empty values in column standard_relation is 0
The number of empty values in column assay_format is 2875
The number of empty values in column assaytype is 1867

**STANFORD DATASET TESTING**

In [25]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
stanford_data = pd.read_csv('Stanford_Dataset_Replication.csv')
stanford_data = stanford_data.drop(['Unnamed: 0'], axis = 1)
stanford_data

,compound_id,standard_inchi_key,target_id,standard_type,standard_relation,standard_value,assay_format,assaytype
0,CHEMBL1232461,AAAQFGUYHFJNHI-SFHVURJKSA-N,P25440,Kd,=,100.00,NaN,NaN
1,CHEMBL1232461,AAAQFGUYHFJNHI-SFHVURJKSA-N,P25440,Kd,=,230.00,NaN,NaN
2,CHEMBL1232461,AAAQFGUYHFJNHI-SFHVURJKSA-N,O60885,Kd,=,65.00,NaN,NaN
3,CHEMBL1232461,AAAQFGUYHFJNHI-SFHVURJKSA-N,O60885,Kd,=,95.00,NaN,NaN
4,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9Z148,Kd,=,18050.00,NaN,binding
5,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9Y6F8,Kd,=,6300.00,NaN,binding
6,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,9.00,NaN,binding
7,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,22.70,NaN,binding
8,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,90.20,NaN,binding
9,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,149.80,NaN,binding
10,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,1776.00,NaN,binding
11,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,9948.00,NaN,binding
12,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,74.00,NaN,binding
13,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,"Q9Y478, P54619, Q13131",Kd,=,487.00,NaN,binding
14,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9Y232,Kd,=,910.00,NaN,binding
15,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9UQB9,Kd,=,10.80,cell_based,binding
16,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9UIK4,Kd,=,450.00,cell_based,binding
17,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9UBF8,Kd,=,3.70,NaN,binding
18,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9UBF8,Kd,=,6.10,NaN,binding
19,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9UBF8,Kd,=,21.00,NaN,binding
20,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9S446,Kd,=,1500.00,NaN,binding
21,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9S446,Kd,=,8800.00,NaN,binding
22,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9HCN6,Kd,=,52000.00,NaN,binding
23,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9HCN6,Kd,=,57000.00,NaN,binding
24,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9HCN6,Kd,=,850000.00,NaN,binding
25,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9HC52,Kd,=,1200.00,NaN,binding
26,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9FBI2,Kd,=,716.00,NaN,binding
27,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9ESU6,Kd,=,5020.00,NaN,binding
28,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9ESU6,Kd,=,8630.00,NaN,binding
29,NaN,ABZSPJVXTTUFAA-UHFFFAOYSA-N,Q9ESU6,Kd,=,17000.00,NaN,binding
...,...,...,...,...,...,...,...,...
2987,CHEMBL3753335,NaN,O14976,Kd,=,660.00,NaN,NaN
2988,CHEMBL3753527,NaN,O14976,Kd,=,1100.00,NaN,NaN
2989,CHEMBL3753792,NaN,O14976,Kd,=,640.00,NaN,NaN
2990,CHEMBL3753857,NaN,O14976,Kd,=,900.00,NaN,NaN
2991,CHEMBL3753916,NaN,O14976,Kd,=,310.00,NaN,NaN
2992,CHEMBL3754235,NaN,O14976,Kd,=,74.00,NaN,NaN
2993,CHEMBL3754300,NaN,O14976,Kd,=,290.00,NaN,NaN
2994,CHEMBL3754728,NaN,O14976,Kd,=,220.00,NaN,NaN
2995,CHEMBL3734798,NaN,O14965,Kd,=,89.24,NaN,binding
2996,CHEMBL3817889,NaN,O14842,Kd,=,4.00,NaN,NaN
2997,CHEMBL3817889,NaN,O14842,Kd,=,7.40,NaN,NaN
2998,CHEMBL3813775,NaN,O14640,Kd,=,268000.00,NaN,NaN
2999,CHEMBL3814041,NaN,O14640,Kd,=,783000.00,NaN,NaN
3000,CHEMBL3814273,NaN,O14640,Kd,=,139000.00,NaN,NaN
3001,CHEMBL3814441,NaN,O14640,Kd,=,251000.00,NaN,NaN
3002,CHEMBL3814506,NaN,O14640,Kd,=,152000.00,NaN,NaN
3003,CHEMBL3814619,NaN,O14640,Kd,=,38300.00,NaN,NaN
3004,CHEMBL3814692,NaN,O14640,Kd,=,186.00,NaN,NaN
3005,CHEMBL3814692,NaN,O14640,Kd,=,11200.00,NaN,NaN
3006,CHEMBL3814761,NaN,O14640,Kd,=,10600.00,NaN,NaN
3007,CHEMBL3814864,NaN,O14640,Kd,=,68400.00,NaN,NaN
3008,CHEMBL3814879,NaN,O14640,Kd,=,62400.00,NaN,NaN
3009,CHEMBL3815146,NaN,O14640,Kd,=,311000.00,NaN,NaN
3010,CHEMBL3780251,NaN,O00257,Kd,=,200.00,NaN,NaN
3011,CHEMBL3780489,NaN,O00257,Kd,=,15500.00,NaN,NaN
3012,CHEMBL3780712,NaN,O00257,Kd,=,800.00,NaN,NaN
3013,CHEMBL3780497,NaN,O00255,Kd,=,23.60,NaN,NaN
3014,CHEMBL3781030,NaN,O00255,Kd,=,6.50,NaN,NaN
3015,CHEMBL3798534,NaN,B4EH87,Kd,=,54000.00,NaN,NaN
3016,CHEMBL3764647,NaN,A4TVL0,Kd,=,3300.00,NaN,NaN

In [40]:
stanford_data_vector = pd.get_dummies(stanford_data, dummy_na = True)
print(stanford_data_vector.shape)
stanford_data_vector

(3017, 1851)

2875

In [43]:
for col in stanford_data.columns:
    missing_cols = stanford_data_vector.columns.str.startswith(str(col) + "_")
    stanford_data_vector.loc[stanford_data[col].isnull(), missing_cols] = np.nan
stanford_data_vector

,standard_value,compound_id_CHEMBL101892,compound_id_CHEMBL103667,compound_id_CHEMBL103817,compound_id_CHEMBL104,compound_id_CHEMBL1090479,compound_id_CHEMBL109074,compound_id_CHEMBL1096380,compound_id_CHEMBL112,compound_id_CHEMBL113142,...,standard_relation_<,standard_relation_=,standard_relation_>,standard_relation_nan,assay_format_biochemical,assay_format_cell_based,assay_format_cell_free,assay_format_nan,assaytype_binding,assaytype_nan
0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,230.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,65.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,95.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,18050.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
5,6300.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
6,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
7,22.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
8,90.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
9,149.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
10,1776.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
11,9948.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
12,74.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
13,487.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
14,910.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
15,10.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
16,450.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
17,3.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
18,6.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
19,21.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
20,1500.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
21,8800.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
22,52000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
23,57000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
24,850000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
25,1200.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
26,716.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
27,5020.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
28,8630.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
29,17000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,660.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2988,1100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2989,640.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2990,900.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2991,310.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2992,74.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2993,290.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2994,220.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2995,89.24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0
2996,4.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2997,7.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2998,268000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2999,783000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3000,139000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3001,251000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3002,152000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3003,38300.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3004,186.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3005,11200.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3006,10600.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3007,68400.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3008,62400.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3009,311000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3010,200.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3011,15500.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3012,800.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3013,23.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3014,6.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3015,54000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3016,3300.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

**Code from http://curiousily.com/data-science/2017/02/02/what-to-do-when-data-is-missing-part-2.html**

In [47]:
import random
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

from keras.objectives import mse
from keras.models import Sequential
from keras.layers.core import Dropout, Dense
from keras.regularizers import l1_l2

from collections import defaultdict
%matplotlib inline

In [46]:
def make_reconstruction_loss(n_features):

    def reconstruction_loss(input_and_mask, y_pred):
        X_values = input_and_mask[:, :n_features]
#         X_values.name = "$X_values"

        missing_mask = input_and_mask[:, n_features:]
        missing_mask.name = "$missing_mask"
        observed_mask = 1 - missing_mask
        observed_mask.name = "$observed_mask"

        X_values_observed = X_values * observed_mask
        X_values_observed.name = "$X_values_observed"

        pred_observed = y_pred * observed_mask
        pred_observed.name = "$y_pred_observed"

        return mse(y_true=X_values_observed, y_pred=pred_observed)
    return reconstruction_loss

In [48]:
def masked_mae(X_true, X_pred, mask):
    masked_diff = X_true[mask] - X_pred[mask]
    return np.mean(np.abs(masked_diff))

In [52]:
class Autoencoder:

    def __init__(self, data,
                 recurrent_weight=0.5,
                 optimizer="adam",
                 dropout_probability=0.5,
                 hidden_activation="relu",
                 output_activation="sigmoid",
                 init="glorot_normal",
                 l1_penalty=0,
                 l2_penalty=0):
        self.data = data.copy()
        self.recurrent_weight = recurrent_weight
        self.optimizer = optimizer
        self.dropout_probability = dropout_probability
        self.hidden_activation = hidden_activation
        self.output_activation = output_activation
        self.init = init
        self.l1_penalty = l1_penalty
        self.l2_penalty = l2_penalty
        
    def _get_hidden_layer_sizes(self):
        n_dims = self.data.shape[1]
        return [
            min(2000, 8 * n_dims),
            min(500, 2 * n_dims),
            int(np.ceil(0.5 * n_dims)),
        ]

    def _create_model(self):

        hidden_layer_sizes = self._get_hidden_layer_sizes()
        first_layer_size = hidden_layer_sizes[0]
        n_dims = self.data.shape[1]
        
        model = Sequential()

        model.add(Dense(
            first_layer_size,
            input_dim= 2 * n_dims,
            activation=self.hidden_activation,
            W_regularizer=l1_l2(self.l1_penalty, self.l2_penalty),
            init=self.init))
        model.add(Dropout(self.dropout_probability))

        for layer_size in hidden_layer_sizes[1:]:
            model.add(Dense(
                layer_size,
                activation=self.hidden_activation,
                W_regularizer=l1_l2(self.l1_penalty, self.l2_penalty),
                init=self.init))
            model.add(Dropout(self.dropout_probability))

        model.add(Dense(
            n_dims,
            activation=self.output_activation,
            W_regularizer=l1_l2(self.l1_penalty, self.l2_penalty),
            init=self.init))

        loss_function = make_reconstruction_loss(n_dims)

        model.compile(optimizer=self.optimizer, loss=loss_function)
        return model

    def fill(self, missing_mask):
        self.data[missing_mask] = -1

    def _create_missing_mask(self):
        if self.data.dtype != "f" and self.data.dtype != "d":
            self.data = self.data.astype(float)

        return np.isnan(self.data)

    def _train_epoch(self, model, missing_mask, batch_size):
        input_with_mask = np.hstack([self.data, missing_mask])
        n_samples = len(input_with_mask)
        n_batches = int(np.ceil(n_samples / batch_size))
        indices = np.arange(n_samples)
        np.random.shuffle(indices)
        X_shuffled = input_with_mask[indices]

        for batch_idx in range(n_batches):
            batch_start = batch_idx * batch_size
            batch_end = (batch_idx + 1) * batch_size
            batch_data = X_shuffled[batch_start:batch_end, :]
            model.train_on_batch(batch_data, batch_data)
        return model.predict(input_with_mask)

    def train(self, batch_size=256, train_epochs=100):
        missing_mask = self._create_missing_mask()
        self.fill(missing_mask)
        self.model = self._create_model()

        observed_mask = ~missing_mask

        for epoch in range(train_epochs):
            X_pred = self._train_epoch(self.model, missing_mask, batch_size)
            observed_mae = masked_mae(X_true=self.data,
                                    X_pred=X_pred,
                                    mask=observed_mask)
            if epoch % 50 == 0:
                print("observed mae:", observed_mae)

            old_weight = (1.0 - self.recurrent_weight)
            self.data[missing_mask] *= old_weight
            pred_missing = X_pred[missing_mask]
            self.data[missing_mask] += self.recurrent_weight * pred_missing
        return self.data.copy()

In [54]:
imputer = Autoencoder(stanford_data_vector.values)
complete_encoded = imputer.train(train_epochs=300, batch_size=256)

C:\Users\willi\Anaconda3\envs\data-x\lib\site-packages\ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(2000, input_dim=3702, activation="relu", kernel_initializer="glorot_normal", kernel_regularizer=<keras.reg...)`
C:\Users\willi\Anaconda3\envs\data-x\lib\site-packages\ipykernel_launcher.py:51: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(500, activation="relu", kernel_initializer="glorot_normal", kernel_regularizer=<keras.reg...)`
C:\Users\willi\Anaconda3\envs\data-x\lib\site-packages\ipykernel_launcher.py:51: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(926, activation="relu", kernel_initializer="glorot_normal", kernel_regularizer=<keras.reg...)`
C:\Users\willi\Anaconda3\envs\data-x\lib\site-packages\ipykernel_launcher.py:58: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1851, activation="sigmoid", kernel_initializer="glorot_normal", kernel_regularizer=<keras.reg...)`

AttributeError: can't set attribute